feature/eng-2577-create-a-new-template-for-unique-point
nextmv-io/sdk pull request #217
Opened 2023-03-09 12:17 UTC by nilsbeck

# Description

This PR adds a new template to show how to use a unique matrix to be passed in an input file.

## Changes

- `main.go` for new template
- `readme.md` for new template
- `input.json` for new template
- test for new template

2023-03-09 14:04 UTC, nmisek requested changes
Mentioned in other PR but I think would be good to have vehicle starts/ends in here

2023-03-14 11:53 UTC, larsbeck commented on templates/unique-matrix-measure/main.go
> +			if refIndex1 != -1 && refIndex2 != -1 {
If they are both `-1` then the cost in `fullMatrix` will be `0`. Is that what we want here?

2023-03-14 12:01 UTC, nilsbeck commented on templates/unique-matrix-measure/main.go
> +			if refIndex1 != -1 && refIndex2 != -1 {
yes, that would mean that we are going from/to a start or end that is not given in the input. Those arcs should be cost 0.

2023-03-14 12:03 UTC, larsbeck submitted a review, later dismissed

2023-03-14 13:05 UTC, nmisek approved these changes, later dismissed

2023-03-14 14:01 UTC, nmisek approved these changes, later dismissed

2023-03-14 14:43 UTC, larsbeck approved these changes

2023-03-14 14:54 UTC, nmisek approved these changes

2023-03-14 15:07 UTC, merged