ENG-1300 ENG-1334 Simplify store generation
nextmv-io/sdk pull request #34
Opened 2022-08-01 03:26 UTC by sebastian-quintero

# Description

Simplify the generation of new stores by changing the signature of the `Store.Generate` func:

```go
Generate(func(Store) Generator) Store
```

A `Generator` may be obtained by using `Eager` or `Lazy`:

```go
func Eager(s ...Store) Generator
func Lazy(c Condition, f func(Store) Store) Generator
```

All other interfaces and unnecessary functions were discarded. In addition, all the examples were updated and the sudoku example was deleted pending revision. Lastly, another method was added to the main `Store` interface: `Validate`. It receives a `store.Condition` to establish operational validity.

## Changes

- Deleted `store.If`, `store.Scope`.
- Deleted `store.Action` and changed `store.Generator` to be `any`.
- Added `store.Eager`, `store.Lazy` and changed the signature of `Store.Generate`.
- Added `.Validate` to the `Store` interface.

2022-08-01 08:46 UTC, davidrijsman requested changes
I remember discussing this before, Eager and Lazy allow the user to do the same thing in two ways. One will be less efficient than the other (in terms of memory). Why would we allow the user to do the same in two ways and one of them being less efficient. I believe we concluded the last time lazy is enough to expose. Is there a reason we need both ways?

2022-08-01 19:02 UTC, sebastian-quintero commented
@davidrijsman And I met to discuss that `Eager` and `Lazy` are both there to make it more ergonomic for the user.

2022-08-02 15:21 UTC, larsbeck approved these changes

2022-08-02 15:34 UTC, davidrijsman approved these changes

2022-08-02 15:37 UTC, merged