Feature/eng 1176 domain tests
nextmv-io/sdk pull request #37
Opened 2022-08-03 06:40 UTC by nilsbeck

# Description
This PR adds `model.MaxInt` and `model.MinInt` to be used as platform independent integers.

## Changes
- adds `model/const.go`

2022-08-03 10:46 UTC, larsbeck approved these changes, later dismissed

2022-08-03 18:51 UTC, sebastian-quintero requested changes
I don't think that a new file is worthwhile. You can throw these at the top of the existing `model.go` file, up to you.

2022-08-03 18:51 UTC, sebastian-quintero commented on model/const.go
> +	MaxInt int = (1<<bits.UintSize)/2 - 1
```suggestion
	// MaxInt is the maximum value for an integer.
	MaxInt int = (1<<bits.UintSize)/2 - 1
```
Add godoc here plz.

2022-08-03 18:51 UTC, sebastian-quintero commented on model/const.go
> +	MinInt     = (1 << bits.UintSize) / -2
```suggestion
	// MinInt is the minimum value for an integer.
	MinInt     = (1 << bits.UintSize) / -2
```
Same here bitte.

2022-08-04 09:03 UTC, larsbeck approved these changes, later dismissed

2022-08-04 10:28 UTC, merschformann commented on model/model.go
> +	MinInt = (1 << bits.UintSize) / -2
Funny how the formatter thinks one of the two is long enough to compress `<<` and for the other it's not. :joy_cat:

2022-08-04 10:28 UTC, merschformann approved these changes, later dismissed
:rocket:

2022-08-04 15:38 UTC, sebastian-quintero submitted a review, later dismissed

2022-08-05 18:00 UTC, sebastian-quintero approved these changes

2022-08-05 18:06 UTC, merschformann approved these changes

2022-08-05 18:32 UTC, merged