Add OSRM, Google, HERE and RoutingKit measure
nextmv-io/sdk pull request #94
Opened 2022-10-07 12:29 UTC by larsbeck

# Description

Adds measures for:
- OSRM
- Google
- HERE
- RoutingKit

2022-10-10 22:12 UTC, nmisek commented on route/google/doc.go
> +it is recommended to pass in waypoints as an encoded as a polyline with "enc:"
```suggestion
it is recommended to pass in waypoints encoded as a polyline with "enc:"
```

2022-10-11 20:20 UTC, sebastian-quintero requested changes
This is a lot 😅 . Some comments regarding licenses and newlines.

2022-10-11 20:20 UTC, sebastian-quintero commented on route/example_option_test.go
> +
Plz remove all of these newlines.

2022-10-11 20:20 UTC, sebastian-quintero commented on route/example_router_test.go
> +
Same here regarding the newline.

2022-10-11 20:20 UTC, sebastian-quintero commented on route/google/client.go
> +// written permission of nextmv.io, inc.
We need to remove these confidentiality headers in all of these files, as they are now under a different, open-source license.

2022-10-11 21:06 UTC, sebastian-quintero commented
@larsbeck I took the liberty of helping you out with some modifications to the `go-buid-test.yml` and `go-lint.yml`. Since we have new go modules, we need to lint and test them. Standing at the root and running with `./...` doesn´t do the trick, we have to stand on each module to lint and test. I used a [job matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs) to be able to do this without the wokflow file being too verbose.

This revealed many things that are still pending. I apologize for giving you more work 😅 .

2022-10-13 20:49 UTC, sebastian-quintero approved these changes, later dismissed

2022-10-17 17:57 UTC, sebastian-quintero approved these changes

2022-10-17 18:04 UTC, merschformann approved these changes
:rocket:

2022-10-17 18:15 UTC, merged