Feature/eng 1692 support quadratic obj functions for mips
nextmv-io/sdk pull request #96
Opened 2022-10-10 22:29 UTC by dirkschumacher

This adds support for quadratic terms in the objective function

2022-10-11 11:21 UTC, larsbeck approved these changes, later dismissed

2022-10-11 11:21 UTC, larsbeck commented on mip/objective.go
> +	IsLinear() bool
Is this lacking a comment?

2022-10-11 19:02 UTC, dirkschumacher commented on mip/objective.go
> +	IsLinear() bool
👍

2022-10-11 20:47 UTC, davidrijsman requested changes, later dismissed

2022-10-11 20:47 UTC, davidrijsman commented on mip/objective.go
> +	NewQuadraticTerm(coefficient float64, variable1, variabl2 Var) QuadraticTerm
Typo variabl2

2022-10-11 20:47 UTC, davidrijsman commented on mip/term.go
> +// of the objective.
in the context ...is not required I think

2022-10-11 21:23 UTC, sebastian-quintero submitted a review, later dismissed
What David said.

2022-10-13 13:13 UTC, sebastian-quintero submitted a review, later dismissed

2022-10-18 12:30 UTC, davidrijsman approved these changes

2022-10-19 14:38 UTC, sebastian-quintero approved these changes

2022-10-23 04:33 UTC, merschformann approved these changes
Great to have quadratic support!

![square-bear](https://user-images.githubusercontent.com/11454283/197373928-331f3b13-8be9-489c-abf3-606e2b2b6008.jpg)

2022-11-01 13:01 UTC, merged